name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ libgtest-dev \
            libbluetooth-dev libdbus-1-dev libmosquitto-dev libpoco-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        make test
        # ctest --output-on-failure

    - name: Generate coverage report
      run: |
        cd build
        make coverage || true
